CREATE TABLE Users (
    UserID CHAR(36) NOT NULL,
    Name VARCHAR(100),
    Email VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID)
);
